name: Measure coverage

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          cache: 'maven'
      - name: Run Coverage
        run: |
          mvn clean verify

      - name: Add coverage to PR
        id: jacoco
        uses: madrapps/jacoco-report@v1.5
        with:
          paths: |
            ${{ github.workspace }}/**/target/site/jacoco/jacoco.xml
          token: ${{ secrets.GITHUB_TOKEN }}
